
name: generate animation

on:
  # run automatically every 6 hours
  schedule:
    - cron: "0 */8 * * *" 
  
  # allows to manually run the job at any time
  workflow_dispatch:
  
  # run on every push on the master branch
  push:
    branches:
    - main
    
jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - name: generate-snake-game-from-github-contribution-grid
      uses: Platane/snk@v2.0.0-rc.2
